### ISSUE TITLE
Lost settings after update to 0.7.0

### ISSUE THREAD

**Issue by eliotcougar** [ZeusLN/zeus#1212]
### Describe the bug

It may be late to report this after the wide release, but after I updated the app from 0.6.6 to 0.7.0 through auto-update on Google Play store, the app has lost all user settings... I had to set up all the nodes again...

### Reproduce

Just auto-update the app on Play Store

### Zeus version

v0.7.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Google Pixel 4XL

### Device operating system

Android 13

**Comment by kaloudis** [comment]
I wonder if this is Android + Google Play only.

I had no issues pulling the APKs manually with Graphene, or updating with TestFlight during dev.

**Comment by Mubelotix** [comment]
Same here, all data appears to be lost

**Comment by kaloudis** [comment]
This appears to be Android specific, iOS not affected. However download platform doesn't make a difference.

**Comment by eliotcougar** [comment]
Lost settings again when updating from 0.7.0 to 0.7.1... 😒

**Comment by dmp1ce** [comment]
OK. Maybe I just won't update until this is resolved.

**Comment by kaloudis** [comment]
This is noted in the release notes. Should be the last time this happens. We moved Android users to a more secure storage mechanism this release.

**Comment by paboum** [comment]
> This is noted in the release notes.

User eXperience shouldn't depend on whether they read release notes or posted a bug report, don't you think? Such a change should at least be explained in a popup when running a new version, let alone announced in advance so that I am not surprised in the field because my wallet stopped working. How do you expect to more people to start using your product if you treat existing ones as "the ones who don't read release notes" and "the ones who complain without a good reason"...

**Comment by kaloudis** [comment]
> > This is noted in the release notes.
> 
> User eXperience shouldn't depend on whether they read release notes or posted a bug report, don't you think? Such a change should at least be explained in a popup when running a new version, let alone announced in advance so that I am not surprised in the field because my wallet stopped working. How do you expect to more people to start using your product if you treat existing ones as "the ones who don't read release notes" and "the ones who complain without a good reason"...

I'm sorry for the inconvenience but you're putting words in my mouth.

We don't have a QA team so we often rely on users to report issues back to us. We ran a beta and no-one reported the issue until the issue was released. It's difficult to catch this issue without more users testing the beta releases. Maybe you could help out and test these releases moving forward.

This has been fixed in v0.7.1 and v0.7.2.
