### ISSUE TITLE
Android: increase resolution of app icon in splash process

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1288]
### Describe the feature

On Android the app launcher icon is briefly shown before moving on to the mascot. The resolution is quite low. It would be nice to make it look sharper.

**Comment by myxmaster** [comment]
not sure what the problem here is... the app launcher icon looks fine on my phone (~392 ppi) and you have the 192x192 version here: https://github.com/ZeusLN/zeus/blob/master/android/app/src/main/res/mipmap-xxxhdpi/zeus.png

i think there is something with google play where you need a 512x512 version, maybe that's what you mean? in that case, you can easily build it from this version: https://github.com/ZeusLN/zeus/blob/master/ios/zeus/Images.xcassets/AppIcon.appiconset/appstore.png

**Comment by kaloudis** [comment]
No longer applicable post redesign
