### ISSUE TITLE
Embedded LND: display Neutrino latency warning

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#2119]

**Comment by Darth-Coin** [comment]
Maybe also we can add somehow a list of available neutrino peers near to the user, from this list, but excepting the Tor ones:
https://bitnodes.io/nodes/?q=NODE_COMPACT_FILTERS

I did some several tests and talked with many Zeus users. Europe users for example can barely use Olympus peer. But can use nicely the Blixt one (located in Germany). The LATAM users are hit hard by this aspect. I couldn't found too many good neutrino peers in south countries. The situation there is desperate. That's why so many users from LATAM trying to use Zeus and Blixt are hit by several sync issues. For some is almost impossible to use Zeus.

**Comment by kaloudis** [comment]
Added in v0.9.0
