### ISSUE TITLE
forwarding transactions view

### ISSUE THREAD

**Issue by rocketjdempsey** [ZeusLN/zeus#397]
On node info, select the forwarding tab.  There is a list of forwarded transactions. This list is limited to some maximum number sorted by descending date. When there are more than a couple hundred forwarded transactions, the list shows the *oldest* and doesn't show recent transactions. The number shown and the limited list is fine but it should show the most recent, not the oldest.

**To Reproduce**
Connect ZeusLN to an active node with more than 200 forwarded transactions. Select the "Node info" icon and then select the "Forwarding" tab. New transactions will not show up. The list will just show the first N transactions. 

**Expected behavior**
The list should show the most recent N transactions 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Debian/Docker
 - Version 10.6
 - Lightning Node: LND version "0.11.99-beta commit=v0.11.0-beta-534-g7e298f143425337448f95019234b22849d64aca3"

**Smartphone (please complete the following information):**
 - Device: Pixel 3xl
 - OS: Android 11
 - Zeus Version v0.4.0

**Additional context**
Should be a simple fix

**Comment by hazrulnizam** [comment]
I have the same problem. I did some digging, and I think it is due to LND's API '/v1/switch' default behaviour of only showing the first 100 forwarding events if called without arguments.

According to [its documentation](https://api.lightning.community/#v1-switch), it is supposed to mirror the behaviour of 'lncli fwdinghistory' which defaults to showing forwarding history of the past 24 hours, but somehow the REST API does not behave the same way.

**Comment by cercatrova21** [comment]
Same problem here. After 100 forwarding transactions, the list will not update and no new forwarding events are showing up.

**Comment by hazrulnizam** [comment]
Looks like this is fixed with [this commit](https://github.com/ZeusLN/zeus/commit/8d4a5d97f87741c5a12990e2705f1c64ae68133c#diff-f86a41a6fd549d1df163728511e7a8916ff2a6f7fb1429e80342886a57029a1b).

Can't wait until this is pushed into release! 😃
