### ISSUE TITLE
Flickering when adding a new node

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#639]
v0.6.0-alpha4

S20 Ultra
Pixel 3a
Pixel 5
Pixel 5a

**Comment by pardus79** [comment]
Pixel 4a also

**Comment by kaloudis** [comment]
Very odd, no issues on my 4a. I wonder why that is.

**Comment by pardus79** [comment]
In case it helps, running Android 12 on 4a.
Had previous alpha installed. Installed new alpha version. It would not boot beyond the splash screen. Cleared cache & data. Rebooted the app and went to the add a node screen. It was flickering.
Cleared data again and it had the same problem. Uninstalled and reinstalled app and had the same flickering problem.

**Comment by dscotese** [comment]
More clues:
Android 8.0.0 on a Galaxy Samsung 7, alpha 4.
I uninstalled the previous version and installed alpha 4.  When I click "Add a new node", I get a form which rapidly toggles between two states.  The two states differ in that under "Node Interface" either it says "LND" or the next field shows up, "Host".  I took several screenshots to capture both states but could only get this one:
![zeusflicker](https://user-images.githubusercontent.com/1767796/144721238-429e3034-7d41-4174-b733-05c7baf4e9f5.jpg)

In the other state, it doesn't say "LND" and everything below that part is higher on the screen so that "Host" is just below "Node Interface".

After another uninstall-reinstall cycle, the problem persists.  To maximize the chances of success, I uninstalled before I restarted my phone.  I also opened the app from the screen that tells me the installation is done.  The problem persists and exactly as I described.

The OS is implicated because every time I use its screenshot feature, the SAME state appears in the screeneshot.  The OS is trying to accommodate something (bad node interface selection widget?) that causes it to delay the screenshot until it's done (switching back to just showing LND).

**Comment by dscotese** [comment]
In the app as it is installed on my device, I can't find an example of a setting which is a dropdown, like the "Node Interface" setting is.  I did find "Language" and "Currency" both of which present several options, but selecting any of them has no effect.  This suggests to me a problem in how the interface framework (ReactJS, I think) is handling selection lists.

**Comment by dscotese** [comment]
I reviewed /views/Settings/AddEditNode.tsx and noticed that the functions defined inside render() (include NodeInterface()) are not called as functions, but their names are used as tag names, whereas the functions defined above render() are called (inside of render()) as functions, like `setNodeConfigurationAsActive` on line 1229.  Is it possible that the mobiles in which this problem (the flicker) shows up are missing some advanced features that automagically fix some problems that might appear in the code?  Probably not.

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1
