### ISSUE TITLE
Feature: Fiat support

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#84]
gives me the heebeegeebees a bit but some users really want it. it will also be a necessity to do before we add merchant features as most merchants will want to peg their prices to fiat

**Comment by mjlamb** [comment]
Yes and would be good to support different currencies, USD, NZD etc. UI, TAP the amount and will cycle sats->btc->fiat denominations.

**Comment by urza** [comment]
Yes, please. 
I was just using Zeus to make my first ever Lightning payment in coffee place few days ago. It is so cool and exciting.
However when making the payment, it is really hard to make sure that you are not paying like 20 eur instead of 2 eur because the merchant did mistake or something... It is somewhat stressful situation when doing the payment onsite, you know, not much cognitive space to say "hey wait a minute it seems there is one order of magnitude many satoshis" :) instead you have barely time to glimpse over their terminal.. so it would be super helpful to see the amount payed in eur/usd or other fiat currencies.
We trust this software with our real money, so please help us feel comfortable and safe. Also when going over payments that were made it would be very helpful to see that in fiat to remember what that was and that it is correct..

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/214

**Comment by ZeusLN** [comment]
Now in v0.2.1

**Comment by ZeusLN** [comment]
https://github.com/ZeusLN/zeus/pull/223
