### ISSUE TITLE
Bug: Incorrect protocol for onion address

### ISSUE THREAD

**Issue by pwltr** [ZeusLN/zeus#861]
**Describe the bug**
When scanning QR Code with onion address cannot connect to node.

**To Reproduce**
example QR Code:
![Screenshot_20220221_181221](https://user-images.githubusercontent.com/8538369/155000715-54842fc8-0d1b-4c15-a342-0c75d6fad7e6.png)

**Additional context**
QR Code produced in Citadel

**Proposed Fix**
When scanning onion addresses it should not prepend "https://" as that will make the host invalid.
https://github.com/ZeusLN/zeus/blob/e71cf8775f3cfc13bd9ba61763db3532c9089410/utils/LndConnectUtils.ts#L35

**Comment by deregs** [comment]
I believe this issue is due to trailing whitespace after the url, not https:// being prepended.

I can repro the issue by scanning the QR - getting 'Error: could not parse url'. But when I scan the QR, and then remove the trailing whitespace from the end of the host field, it connects fine.

This could be fixed on Zeus' end by deleting trailing whitespace from the host field, but can you double check that the lndconnect string is being generated properly in Citadel? It seems like Citadel is inserting an extra space / return character after the host, when it should just be one long string with no spaces / returns. For example, scanning the lndconnect QR code on umbrel with a tor host works because there are no extra spaces in the string.

**Comment by pwltr** [comment]
Ah yes, you're right. Did not catch the trailing whitespace. That might actually cause other problems in Citadel as well. Should probably fix it there. Thanks for looking into this.
