### ISSUE TITLE
Robosats UX

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#865]
https://github.com/Reckless-Satoshi/robosats/issues/44

**Comment by kaloudis** [comment]
Here is the API for Hold Invoices in LND: https://api.lightning.community/#addholdinvoice

**Comment by Reckless-Satoshi** [comment]
Hey @kaloudis cool to see you are working on this fix.

I guess the challenge here is to handle gracefully what happens when Zeus is paying to a Hold Invoice (i.e. an HTLC that might be"IN_FLIGHT" for hours). There might be some tricks around it better than a generic error on a red screen, the payment could go into a "pending" section, for example.

For a most robust approach, @hsjoberg (Blixt) proposed to include a flag/bit in the invoice that let's you know in advance whether the payment will be holded by the receiver. This sounds like a base LN protocol "upgrade", probably will need to make it into a BOLT or something (personally, I have not experience with LN protocol development)

But I also see how being able to generate hold invoices in Zeus would be super cool! (yet not needed to improve UX with RoboSats).

**Comment by hsjoberg** [comment]
> For a most robust approach, @hsjoberg (Blixt) proposed to include a flag/bit in the invoice that let's you know in advance whether the payment will be holded by the receiver. This sounds like a base LN protocol "upgrade", probably will need to make it into a BOLT or something (personally, I have not experience with LN protocol development)

I think it's suited as a [BLIP](https://github.com/lightning/blips) which are more lightweight LN-related things.
An invoice odd feature bit would mean all lightning wallets/nodes would accept them, then for those who understand the hodl bit, they would be able to give a better experience to the user.

**Comment by kaloudis** [comment]
Should be handled correctly now with `v0.8.0`

**Comment by AndySchroder** [comment]
What has actually changed in the UX to make it handled correctly in v0.8.0?
