### ISSUE TITLE
Zeus: linking prefix

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#888]
Support deep links, request from Tim Edwards in telegram group.

**Comment by deregs** [comment]
Messaged Tim about this and can take a stab at it unless someone else gets to it first.

**Comment by tim-edwards** [comment]
Thanks for looking into this for me. I'll try and provide some extra context, and as much information as I can from my deep dive into your codebase.

At THNDR Games we give out sats as prizes. In order to claim, the player needs to have a lightning wallet installed on their device (iOS or Android). By claiming we generate a LNURL withdraw and open this with a deep link.

Initially we used the url scheme "lightning:", which does indeed open a wallet; however it soon became clear that (especially on iOS), the OS just chooses the last installed wallet with the scheme "lightning". Since I believe all wallets have that scheme, at least in my experience this is no good, especially when you want to send your winning sats to a specific wallet  like Zeus. I've been changing this in our platform to use custom deep link url schemes for each wallet, and so far this has been pretty successful.

I believe you can add in a custom scheme (perhaps "zeusln"?) by just editing these three places:

1. 
https://github.com/ZeusLN/zeus/blob/007c516d0152b32be0f869548b0de2acb3e11d79/ios/zeus/Info.plist

In the Info.plist add in another string for CFBundleURLSchemes
`<string>zeusln</string>`

2.
https://github.com/ZeusLN/zeus/blob/906ae36877d6ba36fff96ec9b08615b85e93c691/android/app/src/main/AndroidManifest.xml

In the AndroidManifest, add another Intent filter

```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="zeusln" />
</intent-filter>
```

3.
https://github.com/ZeusLN/zeus/blob/bbfe141bea3f63a37d6c2fadbd8b1ec8c3072740/utils/AddressUtils.ts

Insert another if/else to check for the prefix

```
} else if (input.includes('zeusln:')) {
    value = input.split('zeusln:')[1];
} else {
    value = input;
}
```

-------------

I'm not sure why Zeus wouldn't handle the LNURL after opening with the "lightning" deep link, I can only assume somewhere it gets to the handleAnything.ts script (https://github.com/ZeusLN/zeus/blob/c0003371b125c378115219970428ee93365ac31c/utils/handleAnything.ts) and reaches the findlnurl(value) on line 116. Or at least that's where it looks like it needs to reach.

I wasn't able to find a way of pasting in the text of the LNURL into Zeus, but making a QR code, and scanning that in does work and loads in the invoice which then gets processed correctly. It looks like all the functionality is there, thanks for looking into this and good luck finding out the problem.

If you need any further information please don't hesitate to contact me. Thanks! ⚡

**Comment by Bosch-0** [comment]
Really love this, not being able to open URI's with my desired app is a pain in the ass on iOS.

**Comment by tim-edwards** [comment]
That's an interesting question, I've not tried directly from a QR code using the camera. Testing out on iOS, given the string "LNURL123...123" the OS wants to search for the string in Safari, only by adding a prefix will it attempt to open up in an app.

By prefixing it like "lightning:LNURL123...123", it'll just try and open it up in the last app installed which supports the "lightning" url scheme, this is the issue I have highlighted above. If I prefix with a specific app that I know will handle the LNURL "walletofsatoshi:LNURL123...123", this then opens Wallet of Satoshi and deposits my sats. "somerandomthing:LNURL123...123", this just does nothing the OS doesn't know what to do with it.

Inside the games we don't use QR code, but simply call OpenUrl("").

**Comment by deregs** [comment]
#889
